all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_connection: paramiko

  children:
    dev_stations:
      vars:
        ansible_user: developer
      hosts: 
        10.20.3.216:
