all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_connection: paramiko

  children:
    dev_stations:
      vars:
        ansible_user: administrator
      hosts: 
        192.168.1.49:
