
#TODO idea settings
#TODO internet access rules
#TODO switch drivers
#TODO refactor to roles

- hosts: all
  gather_facts: no
  become: yes

  tasks:
  - name: "Prepare apt cache"
    ignore_errors: yes
    tags: apt
    apt:
      autoremove: yes
      autoclean: yes
      update_cache: yes
      cache_valid_time: 86400 #One day

- hosts: dev_stations
  gather_facts: yes
  become: yes

  pre_tasks:
    - assert:
        that:
          - ansible_processor_vcpus >= 4
          - (ansible_memtotal_mb * 1.024)|int >= 11000 #_Total_ RAM Mb
          - ((ansible_mounts|first).size_available | float / 1000000000) | round(1, 'common') >= 210 #_Free_ disk Gb

  tasks:
    - name: "Set static host ip: Update config"
      tags: network
      template:
        src: templates/01-network-manager-all.yaml.j2
        dest: /etc/netplan/01-network-manager-all.yaml
        owner: root
        group: root
        mode: u=rw,g=r,o=r

    - name: "Set static host ip: Restart service"
      tags: network
      command: netplan apply


    - name: Create developer group
      tags: user4developer
      group:
        name: developers
        state: present

    - name: Add administrator user to developers group
      tags: user4developer
      user:
        name: administrator
        groups: developers
        append: yes

    - name: Create developer user
      tags: user4developer
      user:
        name: developer
        group: developers

    - name: Reset developer user password
      tags: user4developer
      command: passwd -d developer


    - name: Turn on Night Shift
      tags: ux
      become_user: developer
      command: gsettings set org.gnome.settings-daemon.plugins.color night-light-enabled true

    - name: Set wallpaper
      tags: ux
      become_user: developer
      command: gsettings set org.gnome.desktop.background picture-uri "file:///usr/share/backgrounds/budgie/ubuntu_budgie_wallpaper3.jpg"

    - name: Get rid of bluetooth
      tags: ux
      command: systemctl disable bluetooth.service
    
    - name: "Manage power settings: Copy power management config"
      tags: ux
      copy:
        src: logind.conf
        dest: /etc/systemd/
        owner: root
        group: root
        mode: u=rw,g=r,o=r

    - name: "Manage power settings: Apply config"
      tags: ux
      command: systemctl restart systemd-logind.service

    - name: "Manage hibernating settings: Copy config"
      tags: ux
      copy:
        src: grub
        dest: /etc/default/
        owner: root
        group: root
        mode: u=rw,g=r,o=r

    - name: "Manage hibernating settings: Apply config"
      tags: ux
      command: update-grub


    - name: "Install Ansible: Add apt repository"
      tags: ansible
      apt_repository:
        repo: ppa:ansible/ansible
        state: present

    - name: "Install Ansible: Update apt repository"
      tags: ansible
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day

    - name: "Install Ansible: Install package"
      tags: ansible
      apt:
        name: ansible
        state: present


    - name: Install Git
      tags: git
      apt:
        name: git
        state: present

    - name: Install JDK
      tags: java
      apt:
        name: openjdk-8-jdk
        state: present


    - name: "Install Maven: Install package"
      tags: java, maven
      apt:
        name: maven
        state: present

    - name: "Install Maven: Make local repo folder"
      tags: java, maven, maven-repo
      file:
        path: /usr/share/maven-repo/
        state: directory
        owner: developer
        group: developers
        mode: u=rwx,g=rw,o=r
        recurse: yes

    - name: "Install Maven: Configure local repo folder"
      tags: java, maven, maven-repo
      copy:
        src: settings.xml
        dest: /usr/share/maven/conf/


    - name: Install Gradle
      tags: java
      apt:
        name: gradle
        state: present

    - name: Install IntelliJ IDEA CE
      tags: java
      snap:
        name: intellij-idea-community
        classic: yes
        state: present

    - name: "Prepare temporary directories: administrator/Temp"
      tags: ux, chrome
      become_user: administrator
      file:
        path: /home/administrator/Temp
        state: directory

    - name: "Prepare temporary directories: developer/Temp"
      tags: ux, java, maven-warm-up
      become_user: developer
      file:
        path: /home/developer/Temp
        state: directory


    - name: "Install Chrome: Remove Firefox"
      tags: chrome
      apt:
        name: firefox
        state: absent

    - name: "Install Chrome: Download Chrome deb package"
      tags: chrome
      become_user: administrator
      get_url:
        url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        dest: /home/administrator/Temp/

    - name: "Install Chrome: Install deb package"
      tags: chrome
      command: dpkg -i google-chrome-stable_current_amd64.deb
      args:
        chdir: /home/administrator/Temp/

    - name: "Install Chrome: Remove Chrome deb package"
      tags: chrome
      file:
        path: /home/administrator/Temp/google-chrome-stable_current_amd64.deb
        state: absent 


    - name: "Install Docker: Docker CE"
      tags: docker
      apt:
        name: docker.io
        state: present

    - name: Add developer user to Docker group
      tags: user4developer, docker
      user:
        name: developer
        groups: docker
        append: yes

    - name: "Install Docker: Get rid of Permission Denied"
      tags: docker
      command: chmod 666 /var/run/docker.sock

    - name: "Install Docker: Warm up Docker cache with useful images"
      tags: docker, docker-warm-up
      become_user: administrator
      command: docker pull openjdk:8-jre-alpine


    - name: "Warming up maven cache: Clone java project"
      tags: java, maven, maven-warm-up
      become_user: developer
      command: git clone --branch master --depth 1 https://github.com/eugene-krivosheyev/agile-practices-application temp_warmup_project
      args:
        chdir: /home/developer/Temp/

    - name: "Warming up maven cache: Build maven project"
      tags: java, maven, maven-warm-up
      become: yes
      become_user: developer
      become_method: sudo
      command: mvn clean verify
      args:
        chdir: /home/developer/Temp/temp_warmup_project

    - name: "Warming up maven cache: Remove build directory"
      tags: java, maven, maven-warm-up
      become_user: developer
      file:
        path: /home/developer/Temp/temp_warmup_project
        state: absent


    - name: Remove apt dependencies that are no longer required
      tags: apt
      apt:
        autoremove: yes


    - name: Reboot
      tags: reboot
      command: shutdown -r now "Reboot triggered by Ansible script"
      async: 1
      ignore_errors: yes

    - name: Wait for instance up after reboot
      tags: reboot
      wait_for_connection:
        delay: 5
        timeout: 30
      ignore_errors: yes


    - name: "Make developer homedir in-memory: Allow mounting for non-sudo developer account"
      tags: user4developer, homedir4developer
      copy:
        src: sudoers
        dest: /etc/
        owner: root
        group: root
        mode: u=r,g=r,o=r
     
    - name: "Make developer homedir in-memory: Copy in-memory filesystem mount script"
      tags: user4developer, homedir4developer
      copy:
        src: .memhomedir.sh
        dest: /home/developer/
        owner: developer
        group: developers
        mode: u=rwx,g=r,o=r 

    - name: "Make developer homedir in-memory: Enable auto-mount in-memory homedir at logon"
      tags: user4developer, homedir4developer
      copy:
        src: .profile
        dest: /home/developer/
        owner: developer
        group: developers
        mode: u=rw,g=r,o=r

    - name: Reboot
      tags: reboot, homedir4developer
      command: shutdown -r now "Reboot triggered by Ansible script"
      async: 1
      ignore_errors: yes

    - name: Wait for instance up after reboot
      tags: reboot, homedir4developer
      wait_for_connection:
        delay: 5
        timeout: 30
      ignore_errors: yes