- hosts: all
  gather_facts: no
  become: yes

  tasks:
  - name: "Prepare apt cache"
    ignore_errors: yes
    tags: apt
    apt:
      autoremove: yes
      autoclean: yes
      update_cache: yes
      cache_valid_time: 86400 #One day

- hosts: dev_stations
  gather_facts: yes
  become: yes

  pre_tasks:
    - assert:
        that:
          - ansible_processor_vcpus >= 4
          - (ansible_memtotal_mb * 1.024)|int >= 11000 #_Total_ RAM Mb
          - ((ansible_mounts|first).size_available | float / 1000000000) | round(1, 'common') >= 210 #_Free_ disk Gb

  tasks:
    - name: "Install Ansible: Add apt repository"
      tags: ansible
      apt_repository:
        repo: ppa:ansible/ansible
        state: present

    - name: "Install Ansible: Update apt repository"
      tags: ansible
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day

    - name: "Install Ansible: Install package"
      tags: ansible
      apt:
        name: ansible
        state: present


    - name: Install Git
      tags: git
      apt:
        name: git
        state: present

    - name: Install JDK
      tags: java
      apt:
        name: openjdk-8-jdk
        state: present

    - name: Install Maven
      tags: java
      apt:
        name: maven
        state: present

    - name: Install Gradle
      tags: java
      apt:
        name: gradle
        state: present

    - name: Install IntelliJ IDEA CE
      tags: java
      snap:
        name: intellij-idea-community
        classic: yes
        state: present

    - name: Prepare temporary directory
      tags: java, maven-warm-up, chrome
      become_user: administrator
      file:
        path: /home/administrator/Temp
        state: directory

    - name: Remove Firefox
      tags: chrome
      apt:
        name: firefox
        state: absent

    - name: Download Chrome deb package
      tags: chrome
      become_user: administrator
      get_url:
        url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        dest: /home/administrator/Temp/

    - name: Install Chrome
      tags: chrome
      command: dpkg -i google-chrome-stable_current_amd64.deb
      args:
        chdir: /home/administrator/Temp/

    - name: Remove Chrome deb package
      tags: chrome
      file:
        path: /home/administrator/Temp/google-chrome-stable_current_amd64.deb
        state: absent 


    - name: Install Docker CE
      tags: docker
      apt:
        name: docker.io
        state: present


    - name: Git rid of bluetooth
      tags: ux
      command: systemctl disable bluetooth.service

    - name: Turn on Night Shift
      tags: ux
      become_user: administrator
      command: gsettings set org.gnome.settings-daemon.plugins.color night-light-enabled true

    - name: Set wallpaper
      tags: ux
      become_user: administrator
      command: gsettings set org.gnome.desktop.background picture-uri "file:///usr/share/backgrounds/budgie/ubuntu_budgie_wallpaper3.jpg"

    - name: "Manage power settings: Copy power management config"
      tags: ux
      copy:
        src: logind.conf
        dest: /etc/systemd/
        owner: root
        group: root
        mode: u=rw,g=r,o=r

    - name: "Manage power settings: Restart"
      tags: ux
      command: systemctl restart systemd-logind.service


    - name: "Warming up maven cache: Clone java project"
      tags: java, maven-warm-up
      become_user: administrator
      command: git clone --branch master --depth 1 https://github.com/eugene-krivosheyev/agile-practices-application temp_warmup_project
      args:
        chdir: /home/administrator/Temp/

    - name: "Warming up maven cache: Build maven project"
      tags: java, maven-warm-up
      become_user: administrator
      command: mvn clean verify
      args:
        chdir: /home/administrator/Temp/temp_warmup_project

    - name: "Warming up maven cache: Remove build directory"
      tags: java, maven-warm-up
      become_user: administrator
      file:
        path: /home/administrator/Temp/temp_warmup_project
        state: absent


    - name: Remove apt dependencies that are no longer required
      tags: apt
      apt:
        autoremove: yes

