# TODO: 
# temorary/session developer home folder
# internet access rules
# refactor to roles

- hosts: all
  gather_facts: no
  become: yes

  tasks:
  - name: "Prepare apt cache"
    ignore_errors: yes
    tags: apt
    apt:
      autoremove: yes
      autoclean: yes
      update_cache: yes
      cache_valid_time: 86400 #One day

- hosts: dev_stations
  gather_facts: yes
  become: yes

  pre_tasks:
    - assert:
        that:
          - ansible_processor_vcpus >= 4
          - (ansible_memtotal_mb * 0.001024) | int >= 12
          - ((ansible_mounts|first).size_available | float / 1000000000) >= 200
      tags: not_for_virtual_box_test_env

  tasks:
    - name: "Set static host ip: Update config"
      tags: network
      template:
        src: templates/01-network-manager-all.yaml.j2
        dest: /etc/netplan/01-network-manager-all.yaml
        owner: root
        group: root
        mode: u=rw,g=r,o=r

    - name: "Set static host ip: Restart service"
      tags: network
      command: netplan apply

    - name: Get rid of bluetooth
      tags: ux
      command: systemctl disable bluetooth.service
    
    - name: "Manage power settings: Copy power management config"
      tags: ux
      copy:
        src: logind.conf
        dest: /etc/systemd/
        owner: root
        group: root
        mode: u=rw,g=r,o=r

    - name: "Manage power settings: Apply config"
      tags: ux
      command: systemctl restart systemd-logind.service

    - name: "Manage hibernating settings: Copy config"
      tags: ux
      copy:
        src: grub
        dest: /etc/default/
        owner: root
        group: root
        mode: u=rw,g=r,o=r

    - name: "Manage hibernating settings: Apply config"
      tags: ux
      command: update-grub


    - name: "Install Ansible: Add apt repository"
      tags: apt, ansible
      apt_repository:
        repo: ppa:ansible/ansible
        state: present
      ignore_errors: yes

    - name: "Install Ansible: Update apt repository"
      tags: ansible
      apt:
        autoremove: yes
        autoclean: yes
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day
      ignore_errors: yes

    - name: "Install Ansible: Install package"
      tags: ansible
      apt:
        name: ansible
        state: present


    - name: Install Git
      tags: git
      package:
        name: git
        state: present

    - name: Install JDK
      tags: java
      package:
        name: openjdk-8-jdk-headless
        state: present


    - name: "Install Maven: Install package"
      tags: java, maven
      package:
        name: maven
        state: present

    - name: "Install Maven: Make local repo folder"
      tags: java, maven, maven-repo
      file:
        path: /usr/share/maven-repo/
        state: directory
        owner: administrator
        group: administrator
        mode: u=rwx,g=rwx,o=r
        recurse: yes

    - name: "Install Maven: Configure local repo"
      tags: java, maven, maven-repo
      copy:
        src: settings.xml
        dest: /usr/share/maven/conf/


    - name: Install Gradle
      tags: java
      package:
        name: gradle
        state: present


    - name: "Install IntelliJ IDEA CE: IDE"
      tags: java, idea
      snap:
        name: intellij-idea-community
        classic: yes
        state: present

    - name: "Install IntelliJ IDEA CE: Settings"
      tags: java, idea
      copy:
        src: settings.zip
        dest: /home/administrator/.Idea*/config/
        owner: administrator
        group: administrator
        mode: u=rwx,g=rwx,o=r


    - name: "Prepare temporary directories: administrator/Temp"
      tags: ux, java, maven-warm-up
      file:
        path: /home/administrator/Temp
        state: directory
        owner: administrator
        group: administrator
        mode: u=rwx,g=rwx,o=r
        recurse: yes


    - name: "Install Chromium: Remove Firefox"
      tags: chromium
      package:
        name: firefox
        state: absent

    - name: "Install Chromium: Install package"
      tags: chromium
      package: 
        name: chromium-browser
        state: present        


    - name: "Install Docker: Docker CE"
      tags: docker
      package:
        name: docker.io
        state: present

    - name: Add user to Docker group
      tags: docker
      user:
        name: administrator
        groups: docker
        append: yes

    - name: "Install Docker: Get rid of Permission Denied"
      tags: docker
      command: chmod 666 /var/run/docker.sock


    - name: "Install Docker: Warm up Docker cache with useful images"
      tags: docker, docker-warm-up
      command: docker pull openjdk:8-jre-alpine


    - name: "Warming up maven cache: Clone java project"
      tags: java, maven, maven-warm-up
      git:
        repo: https://github.com/eugene-krivosheyev/agile-practices-application
        dest: /home/administrator/Temp/agile-practices-application
        force: yes

    - name: "Warming up maven cache: Ensure ownership of maven repo"
      tags: java, maven, maven-repo
      file:
        path: /usr/share/maven-repo/
        owner: administrator
        group: administrator
        mode: u=rwx,g=rwx,o=r
        recurse: yes

    - name: "Warming up maven cache: Build maven project"
      tags: java, maven, maven-warm-up
      become_user: administrator
      command: mvn clean verify
      args:
        chdir: /home/administrator/Temp/agile-practices-application

    - name: "Warming up maven cache: Remove build directory"
      tags: java, maven, maven-warm-up
      file:
        path: /home/administrator/Temp/agile-practices-application
        state: absent


    - name: Remove apt dependencies that are no longer required
      tags: apt
      apt:
        autoremove: yes


    - name: Reboot
      tags: reboot
      command: shutdown -r now "Reboot triggered by Ansible script"
      async: 1
      ignore_errors: yes

    - name: Wait for instance up after reboot
      tags: reboot
      wait_for_connection:
        delay: 5
        timeout: 30
      ignore_errors: yes
